#!/bin/sh
#this script will be run when project updated on server

#/path/to/your/repository.git/hooks
HOOKS_DIR=$(dirname "$(readlink -f "$0")")

REPO_DIR=$(dirname "$HOOKS_DIR")

#get name of $REPO_DIR
#/path/to/your/repository.git
REPO_NAME=$(basename "$REPO_DIR" .git)

# set branch
BRANCH="main"

#set work tree path
#/path/to/your/repository
WORK_TREE=$(dirname "$REPO_DIR")/$REPO_NAME
#check WORK_TREE has been created
if [ ! -d "$WORK_TREE" ]; then
    echo "Creating work tree at $WORK_TREE"
    mkdir $WORK_TREE
fi

echo "REPO_DIR ----> $REPO_DIR"
echo "REPO_NAME ----> $REPO_NAME"
echo "WORK_TREE ----> $WORK_TREE"

#set service path
SERVICE_DIR="/etc/systemd/system"
SERVICE_PATH=$SERVICE_DIR/$REPO_NAME.service


#set env path
ENVIRONMENT_DIR=$WORK_TREE/venv
# Check if the virtual environment directory exists
if [ ! -d "$ENVIRONMENT_DIR" ]; then
    echo "Creating virtual environment at $ENVIRONMENT_DIR"
    python3 -m venv $ENVIRONMENT_DIR
fi


while read oldrev newrev ref
do
        # only checking out the main (or whatever branch you would like to deploy)
        if [ "$ref" = "refs/heads/$BRANCH" ];
        then
                echo "Ref $ref received. Deploying ${BRANCH} branch on server..."
                git --work-tree="${WORK_TREE}" --git-dir="${GIT_DIR}" checkout -f ${BRANCH}

                #update pip
                $ENVIRONMENT_DIR/bin/pip install --upgrade pip

                # Install requirements
                $ENVIRONMENT_DIR/bin/pip install -r $WORK_TREE/requirements.txt
                echo "requirements installed"

                #check service file has been created
                if [ ! -f "$SERVICE_PATH" ]; then
                    echo "Creating service file at $SERVICE_PATH"
                    #create service file
                    sudo sh -c "echo '[Unit]
Description=$REPO_NAME Service
After=network.target

[Service]
User=ubuntu
WorkingDirectory=$WORK_TREE
ExecStart=$WORK_TREE/start.sh
Restart=always

[Install]
WantedBy=multi-user.target' > $SERVICE_PATH"
                    echo "The Service has been created --> $SERVICE_PATH"

                    #reload service
                    sudo systemctl daemon-reload
                    #enable service
                    sudo systemctl enable $REPO_NAME
                    #start service
                    sudo systemctl start $REPO_NAME
                    #exit from root
                else
                    echo  "Restart service"
                    #restart service by root
                    sudo systemctl restart $REPO_NAME

                fi
                sudo systemctl status $REPO_NAME
                exit
        else
                echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
        fi
done