name: Push to Server

on:
  push:
    branches:
      - main

jobs:
  push_to_origin:
    environment: DEPLOY
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Environment Variables
        run: |
          echo "OPENAI_API_KEY: $OPENAI_API_KEY"
          echo "TEST: $TEST"
  



    
