name: Push to Server

on:
  push:
    branches:
      - main

jobs:
  push_to_origin:
    environment: DEPLOY
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Environment Variables
        run: |
          # get and echo environment secert "OPENAI_API_KEY
          echo "secret: ${{ secrets.OPENAI_API_KEY }}"
          echo "test: ${{ vars.TEST }}"




    
