name: Push to Server

on:
  push:
    branches:
      - main

jobs:
  push_to_origin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code


      - name: Echo Environment Variables
        run: |
          api = {{secrets.OPENAI_API_KEY}}
          echo $api



    
