name: Push to Server

on:
  push:
    branches:
      - main

jobs:
  push_to_origin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Get Environment Variables
        env:
          API: ${{secrets.OPENAI_API_KEY}}
        run: |
          echo "API: $API"
  


    